---
api_version: catalog/v1
type: Integration
metadata:
  namespace: prometheus
  name: node-exporter-metrics
spec:
  class: community
  provider: monitoring
  display_name: Prometheus Node Exporter Metrics
  short_description: Collect metrics from Prometheus node_exporter
  supported_platforms:
    - darwin
    - linux
  tags:
    - metrics
    - prometheus
    - node_exporter
  contributors:
    - "@sensu"
    - "@thoward"
    - "@nixwiz"
  prompts:
    - type: section
      title: Node Exporter Metrics HTTP Endpoint Configuration
    - type: markdown
      body: |
        Provide these configuration parameters for the Prometheus `node_exporter` HTTP endpoint:

        * Target URL to collect metrics from, such as `https://127.0.0.1:9100/metrics`, separated into:
          * Protocol (`http` or `https`)
          * Host (hostname, IP address, or domain name)
          * Port number
          * Path (e.g. `/metrics`)
        * Interval for collecting metrics from the endpoint (in seconds)
    - type: question
      name: protocol
      required: true
      input:
        type: string
        title: Target URL protocol
        description: >-
          Select the protocol for the Prometheus `node_exporter` target URL (`http` or `https`)
        enum:
          - http
          - https
        default: https
    - type: question
      name: host
      required: true
      input:
        type: string
        title: Target URL host
        description: >-
          Enter the host for the Prometheus `node_exporter` target URL
        default: 127.0.0.1
    - type: question
      name: port
      required: true
      input:
        type: integer
        title: Target URL port
        description: >-
          Enter the port for the Prometheus `node_exporter` target URL (`node_exporter` default is `9100`)
        default: 9100
    - type: question
      name: path
      required: true
      input:
        type: string
        title: Target URL path
        description: >-
          Enter the path for the Prometheus `node_exporter` target URL (MUST begin with `/`)
        default: "/metrics"
    - type: question
      name: interval
      input:
        type: integer
        title: Interval
        description: >-
          Specify the metrics collection interval, in seconds (60 = 1 minute, 300 = 5 minutes, 600 = 10 minutes)
        default: 30
    - type: section
      title: Check Labels and Sensu Subscriptions
    - type: markdown
      body: |
        Specify the subscriptions for Sensu agents that should execute the `node-exporter-metrics` check and the metadata labels to add to the check definition.
    - type: question
      name: subscriptions
      input:
        type: array
        items:
          type: string
          title: Subscriptions
          ref: core/v2/entity/subscriptions
        default:
          - prometheus
          - node_exporter
    - type: question
      name: labels
      input:
        type: object
        title: Check labels
        description: Add metadata labels for the `node-exporter-metrics` check
        format: io.sensu.meta.label
        additionalProperties:
          type: string
    - type: section
      title: Pipeline Configuration
    - type: markdown
      body: |
        Name the [pipelines] you want to use to process Prometheus Node Exporter Metrics integration data.

        [pipelines]: https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-process/pipelines/
    - type: question
      name: metrics_pipeline
      required: false
      input:
        type: string
        title: Metrics pipeline name
        description: >-
          Which pipeline do you want to use to process the metrics this integration collects?
        ref: core/v2/pipeline/metadata/name
        refFilter: .labels.provider == "metrics"
  resource_patches:
    - resource:
        api_version: core/v2
        type: CheckConfig
        name: node-exporter-metrics
      patches:
        - op: replace
          path: /metadata/labels
          value: labels
        - op: replace
          path: /spec/command
          value: >-
            http-get
            --timeout 10
            --url "[[protocol]]://[[host]]:[[port]][[path]]"
        - op: replace
          path: /spec/interval
          value: interval
        - op: replace
          path: /spec/subscriptions
          value: subscriptions
        - op: add
          path: /spec/output_metric_tags/-
          value:
            name: "url"
            value: "[[protocol]]://[[host]]:[[port]][[path]]"
        - op: add
          path: /spec/pipelines/-
          value:
            api_version: core/v2
            type: Pipeline
            name: "[[metrics_pipeline]]"
  post_install:
    - type: section
      title: Success
    - type: markdown
      body: |
        You enabled the Prometheus Node Exporter Metrics integration for `[[protocol]]://[[host]]:[[port]][[path]]`.
        
        The `node-exporter-metrics` check will run for all Sensu agents with these subscriptions: [[subscriptions]]. 