---
api_version: catalog/v1
type: Integration
metadata:
  namespace: docker
  name: docker-monitoring
spec:
  class: community
  provider: monitoring
  display_name: Docker Monitoring
  short_description: Monitor Docker daemon conditions and collect Docker metrics
  supported_platforms:
    - linux
  tags:
    - docker
    - containers
    - metrics
    - prometheus
  contributors:
    - "@sensu"
    - "@thoward"
  prompts:
    - type: section
      title: Docker Metrics Endpoint Configuration
    - type: markdown
      body: |
        Provide these configuration parameters for the Docker `/metrics` endpoint:

        * Target URL to collect metrics from, such as `https://127.0.0.1:9323/metrics`, separated into:
          * Protocol (`http` or `https`)
          * Host (hostname, IP address, or domain name)
          * Port number
          * Path (`/metrics`)
        * Interval for collecting metrics from the endpoint (in seconds)
    - type: question
      name: protocol
      required: true
      input:
        type: string
        title: Target URL protocol
        description: >-
          Select the protocol for the Docker target URL (`http` or `https`)
        enum:
          - http
          - https
        default: http
    - type: question
      name: host
      required: true
      input:
        type: string
        title: Target URL host
        description: >-
          Enter the host for the Docker target URL
        default: 127.0.0.1
    - type: question
      name: port
      required: true
      input:
        type: integer
        title: Target URL port
        description: >-
          Enter the port for the Docker target URL (Docker default is `9323`)
        default: 9323
    - type: question
      name: path
      required: true
      input:
        type: string
        title: Target URL path
        description: >-
          Enter the path for the Docker target URL (`/metrics`)
        default: "/metrics"
    - type: question
      name: interval
      input:
        type: integer
        title: Interval
        description: >-
          Specify the metrics collection interval, in seconds (60 = 1 minute, 300 = 5 minutes, 600 = 10 minutes)
        default: 30
    - type: question
      name: labels
      input:
        type: object
        title: Check labels
        description: Add metadata labels for the `docker-daemon-metrics` check
        format: io.sensu.meta.label
        additionalProperties:
          type: string
    - type: section
      title: Sensu Subscriptions
    - type: markdown
      body: |
        Specify the subscriptions for Sensu agents that should execute the `docker-daemon-metrics` check
    - type: question
      name: subscriptions
      input:
        type: array
        items:
          type: string
          title: Subscriptions
          ref: core/v2/entity/subscriptions
        default:
          - docker
          - docker-daemon
          - docker-machine
    - type: section
      title: Pipeline Configuration
    - type: markdown
      body: |
        Name the [pipelines] you want to use to process DNS Monitoring integration data.

        [pipelines]: https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-process/pipelines/
    - type: question
      name: alert_pipeline
      required: false
      input:
        type: string
        title: Alert pipeline name
        description: >-
          Which pipeline do you want to use for alerts due to failures this integration detects?
        ref: core/v2/pipeline/metadata/name
        refFilter: .labels.provider == "alerts"
    - type: question
      name: incident_pipeline
      required: false
      input:
        type: string
        title: Incident pipeline name
        description: >-
          Which pipeline do you want to use to process incidents due to failures this integration detects?
        ref: core/v2/pipeline/metadata/name
        refFilter: .labels.provider == "incidents"
    - type: question
      name: metrics_pipeline
      required: false
      input:
        type: string
        title: Metrics pipeline name
        description: >-
          Which pipeline do you want to use to process the metrics this integration collects?
        ref: core/v2/pipeline/metadata/name
        refFilter: .labels.provider == "metrics"
  resource_patches:
    - resource:
        api_version: core/v2
        type: CheckConfig
        name: docker-daemon-metrics
      patches:
        - op: replace
          path: /metadata/labels
          value: labels
        - op: replace
          path: /spec/command
          value: >-
            http-get
            --timeout 10
            --url "[[protocol]]://[[host]]:[[port]][[path]]"
        - op: replace
          path: /spec/subscriptions
          value: subscriptions
        - op: add
          path: /spec/output_metric_tags/-
          value:
            name: "url"
            value: "[[protocol]]://[[host]]:[[port]][[path]]"
        - op: add
          path: /spec/pipelines/-
          value:
            api_version: core/v2
            type: Pipeline
            name: "[[metrics_pipeline]]"
  post_install:
    - type: section
      title: Success
    - type: markdown
      body: |
        You enabled the Docker Monitoring integration for `[[protocol]]://[[host]]:[[port]][[path]]`.

        The `docker-daemon-metrics` check will run for all Sensu agents with these subscriptions: [[subscriptions]].